Public Class frmMenu

    Private Sub cargarDatos(sender As Object, e As EventArgs) Handles ucPuntuacion1.Load
        jugador1()
        jugador2()
        jugador3()
        jugador4()
        jugador5()
        jugador6()
        jugador7()
        jugador8()
        jugador9()
        jugador10()
    End Sub

    Private Sub tsbPlay_Click(sender As Object, e As EventArgs) Handles tsbPlay.Click
        MediaPlayer.Ctlcontrols.play()
        tsbPlay.Image = My.Resources.Resource1.pausa

    End Sub

    Private Sub PanelMediaPlayer_DragEnter(sender As Object, e As DragEventArgs) Handles PanelMediaPlayer.DragEnter
        If (e.Data.GetDataPresent(DataFormats.FileDrop)) Then
            e.Effect = DragDropEffects.Copy
        End If
    End Sub

    Public Sub jugador1()
        ucPuntuacion1.setCampeon(My.Resources.Imagenes.shen)
        ucPuntuacion1.setNivel("13")
        ucPuntuacion1.setHechizo1(My.Resources.Imagenes.tp)
        ucPuntuacion1.setCHechizo2(My.Resources.Imagenes.flash)
        ucPuntuacion1.setKDA("2/0/5")
        ucPuntuacion1.setMinions("200")
        ucPuntuacion1.setObjeto1(My.Resources.Imagenes.guardiancontrol)
        ucPuntuacion1.setObjeto2(My.Resources.Imagenes.escudodoran)
        ucPuntuacion1.setObjeto3(My.Resources.Imagenes.botasresistencia)
        ucPuntuacion1.setObjeto4(My.Resources.Imagenes.tiamat)
        ucPuntuacion1.setObjeto5(My.Resources.Imagenes.rostroespiritual)
        ucPuntuacion1.setObjeto6(My.Resources.Imagenes.capafuegosolar)
        ucPuntuacion1.setWard(My.Resources.Imagenes.wardazul)

        UcJugador1.setFoto(My.Resources.Imagenes.vizic)
        UcJugador1.setNombre("Vizicsacsi")
        UcJugador1.setNombreReal("Tamás Kiss")
        UcJugador1.setRol("Toplaner")
        UcJugador1.setNacionalidad(My.Resources.Imagenes.hungria)
    End Sub

    Public Sub jugador2()
        ucPuntuacion2.setCampeon(My.Resources.Imagenes.graves)
        ucPuntuacion2.setNivel("11")
        ucPuntuacion2.setHechizo1(My.Resources.Imagenes.smite)
        ucPuntuacion2.setCHechizo2(My.Resources.Imagenes.flash)
        ucPuntuacion2.setKDA("1/2/1")
        ucPuntuacion2.setMinions("123")
        ucPuntuacion2.setObjeto2(My.Resources.Imagenes.cristalrubi)
        ucPuntuacion2.setObjeto3(My.Resources.Imagenes.botasresistencia)
        ucPuntuacion2.setObjeto4(My.Resources.Imagenes.bacteriofago)
        ucPuntuacion2.setObjeto5(My.Resources.Imagenes.sobremaleficios)
        ucPuntuacion2.setObjeto6(My.Resources.Imagenes.guerrero)
        ucPuntuacion2.setWard(My.Resources.Imagenes.wardquitarwards)

        UcJugador2.setFoto(My.Resources.Imagenes.xerxe)
        UcJugador2.setNombre("Xerxe")
        UcJugador2.setNombreReal("Andrei Dragomir")
        UcJugador2.setRol("Jungler")
        UcJugador2.setNacionalidad(My.Resources.Imagenes.rumania)
    End Sub

    Public Sub jugador3()
        ucPuntuacion3.setCampeon(My.Resources.Imagenes.jayce)
        ucPuntuacion3.setNivel("13")
        ucPuntuacion3.setHechizo1(My.Resources.Imagenes.flash)
        ucPuntuacion3.setCHechizo2(My.Resources.Imagenes.extenuacion)
        ucPuntuacion3.setKDA("0/4/2")
        ucPuntuacion3.setMinions("178")
        ucPuntuacion3.setObjeto1(My.Resources.Imagenes.espadalarga)
        ucPuntuacion3.setObjeto2(My.Resources.Imagenes.lagrima)
        ucPuntuacion3.setObjeto3(My.Resources.Imagenes.gemavida)
        ucPuntuacion3.setObjeto4(My.Resources.Imagenes.botasresistencia)
        ucPuntuacion3.setObjeto5(My.Resources.Imagenes.bacteriofago)
        ucPuntuacion3.setObjeto6(My.Resources.Imagenes.youmuu)
        ucPuntuacion3.setWard(My.Resources.Imagenes.wardnormal)

        UcJugador3.setFoto(My.Resources.Imagenes.exileh)
        UcJugador3.setNombre("Exileh")
        UcJugador3.setNombreReal("Fabian Schubert")
        UcJugador3.setRol("Midlaner")
        UcJugador3.setNacionalidad(My.Resources.Imagenes.alemania)
    End Sub

    Public Sub jugador4()
        ucPuntuacion4.setCampeon(My.Resources.Imagenes.varus)
        ucPuntuacion4.setNivel("12")
        ucPuntuacion4.setHechizo1(My.Resources.Imagenes.flash)
        ucPuntuacion4.setCHechizo2(My.Resources.Imagenes.curar)
        ucPuntuacion4.setKDA("1/2/1")
        ucPuntuacion4.setMinions("208")
        ucPuntuacion4.setObjeto1(My.Resources.Imagenes.galleta)
        ucPuntuacion4.setObjeto2(My.Resources.Imagenes.guardiancontrol)
        ucPuntuacion4.setObjeto3(My.Resources.Imagenes.lagrima)
        ucPuntuacion4.setObjeto4(My.Resources.Imagenes.botascdr)
        ucPuntuacion4.setObjeto5(My.Resources.Imagenes.youmuu)
        ucPuntuacion4.setObjeto6(My.Resources.Imagenes.filonoche)
        ucPuntuacion4.setWard(My.Resources.Imagenes.wardazul)

        UcJugador4.setFoto(My.Resources.Imagenes.samux)
        UcJugador4.setNombre("Samux")
        UcJugador4.setNombreReal("Samuel Fernández")
        UcJugador4.setRol("ADCarry")
        UcJugador4.setNacionalidad(My.Resources.Imagenes.españa)
    End Sub

    Public Sub jugador5()
        ucPuntuacion5.setCampeon(My.Resources.Imagenes.zyra)
        ucPuntuacion5.setNivel("10")
        ucPuntuacion5.setHechizo1(My.Resources.Imagenes.flash)
        ucPuntuacion5.setCHechizo2(My.Resources.Imagenes.extenuacion)
        ucPuntuacion5.setKDA("0/3/1")
        ucPuntuacion5.setMinions("16")
        ucPuntuacion5.setObjeto1(My.Resources.Imagenes.guardiancontrol)
        ucPuntuacion5.setObjeto2(My.Resources.Imagenes.cristalrubi)
        ucPuntuacion5.setObjeto3(My.Resources.Imagenes.tomoap)
        ucPuntuacion5.setObjeto4(My.Resources.Imagenes.varaap)
        ucPuntuacion5.setObjeto5(My.Resources.Imagenes.botasrapidez)
        ucPuntuacion5.setObjeto6(My.Resources.Imagenes.ojovigilantes)
        ucPuntuacion5.setWard(My.Resources.Imagenes.wardquitarwards)

        UcJugador5.setFoto(My.Resources.Imagenes.hylissang)
        UcJugador5.setNombre("Hylissang")
        UcJugador5.setNombreReal("Zdravets Galabor")
        UcJugador5.setRol("Support")
        UcJugador5.setNacionalidad(My.Resources.Imagenes.bulgaria)
    End Sub

    Public Sub jugador6()
        ucPuntuacion6.setCampeon(My.Resources.Imagenes.renekton)
        ucPuntuacion6.setNivel("15")
        ucPuntuacion6.setHechizo1(My.Resources.Imagenes.flash)
        ucPuntuacion6.setCHechizo2(My.Resources.Imagenes.tp)
        ucPuntuacion6.setKDA("0/0/6")
        ucPuntuacion6.setMinions("250")
        ucPuntuacion6.setObjeto1(My.Resources.Imagenes.hidratitanica)
        ucPuntuacion6.setObjeto2(My.Resources.Imagenes.cuchilla)
        ucPuntuacion6.setObjeto3(My.Resources.Imagenes.habitoespectro)
        ucPuntuacion6.setObjeto4(My.Resources.Imagenes.tabi)
        ucPuntuacion6.setObjeto5(My.Resources.Imagenes.doran)
        ucPuntuacion6.setWard(My.Resources.Imagenes.wardazul)

        UcJugador6.setFoto(My.Resources.Imagenes.alphari)
        UcJugador6.setNombre("Alphari")
        UcJugador6.setNombreReal("Barney Morris")
        UcJugador6.setRol("Toplaner")
        UcJugador6.setNacionalidad(My.Resources.Imagenes.reinounido)
    End Sub

    Public Sub jugador7()
        ucPuntuacion7.setCampeon(My.Resources.Imagenes.elise)
        ucPuntuacion7.setNivel("13")
        ucPuntuacion7.setHechizo1(My.Resources.Imagenes.smite)
        ucPuntuacion7.setCHechizo2(My.Resources.Imagenes.flash)
        ucPuntuacion7.setKDA("5/1/3")
        ucPuntuacion7.setMinions("120")
        ucPuntuacion7.setObjeto1(My.Resources.Imagenes.liandry)
        ucPuntuacion7.setObjeto2(My.Resources.Imagenes.ecosrunicos)
        ucPuntuacion7.setObjeto3(My.Resources.Imagenes.codice)
        ucPuntuacion7.setObjeto4(My.Resources.Imagenes.botascdr)
        ucPuntuacion7.setObjeto5(My.Resources.Imagenes.tomoap)
        ucPuntuacion7.setWard(My.Resources.Imagenes.wardquitarwards)

        UcJugador7.setFoto(My.Resources.Imagenes.kakao)
        UcJugador7.setNombre("KaKAO")
        UcJugador7.setNombreReal("Byung-Kwon Lee")
        UcJugador7.setRol("Jungler")
        UcJugador7.setNacionalidad(My.Resources.Imagenes.koreasur)
    End Sub

    Public Sub jugador8()
        ucPuntuacion8.setCampeon(My.Resources.Imagenes.orianna)
        ucPuntuacion8.setNivel("15")
        ucPuntuacion8.setHechizo1(My.Resources.Imagenes.fantasmal)
        ucPuntuacion8.setCHechizo2(My.Resources.Imagenes.flash)
        ucPuntuacion8.setKDA("6/0/4")
        ucPuntuacion8.setMinions("216")
        ucPuntuacion8.setObjeto1(My.Resources.Imagenes.zhonyas)
        ucPuntuacion8.setObjeto2(My.Resources.Imagenes.varaedades)
        ucPuntuacion8.setObjeto3(My.Resources.Imagenes.bastonvacio)
        ucPuntuacion8.setObjeto4(My.Resources.Imagenes.tabi)
        ucPuntuacion8.setObjeto5(My.Resources.Imagenes.anillodoran)
        ucPuntuacion8.setWard(My.Resources.Imagenes.wardnormal)

        UcJugador8.setFoto(My.Resources.Imagenes.powerofevil)
        UcJugador8.setNombre("PowerOfEvil")
        UcJugador8.setNombreReal("Tristan Schrage")
        UcJugador8.setRol("Midlaner")
        UcJugador8.setNacionalidad(My.Resources.Imagenes.alemania)
    End Sub

    Public Sub jugador9()
        ucPuntuacion9.setCampeon(My.Resources.Imagenes.jhin)
        ucPuntuacion9.setNivel("13")
        ucPuntuacion9.setHechizo1(My.Resources.Imagenes.flash)
        ucPuntuacion9.setCHechizo2(My.Resources.Imagenes.curar)
        ucPuntuacion9.setKDA("2/0/5")
        ucPuntuacion9.setMinions("200")
        ucPuntuacion9.setObjeto1(My.Resources.Imagenes.filonoche)
        ucPuntuacion9.setObjeto2(My.Resources.Imagenes.youmuu)
        ucPuntuacion9.setObjeto3(My.Resources.Imagenes.tabi)
        ucPuntuacion9.setObjeto4(My.Resources.Imagenes.capacritico)
        ucPuntuacion9.setWard(My.Resources.Imagenes.wardazul)

        UcJugador9.setFoto(My.Resources.Imagenes.hanssama)
        UcJugador9.setNombre("Hans Sama")
        UcJugador9.setNombreReal("Steven Liv")
        UcJugador9.setRol("AD Carry")
        UcJugador9.setNacionalidad(My.Resources.Imagenes.francia)
    End Sub

    Public Sub jugador10()
        ucPuntuacion10.setCampeon(My.Resources.Imagenes.malzahar)
        ucPuntuacion10.setNivel("11")
        ucPuntuacion10.setHechizo1(My.Resources.Imagenes.flash)
        ucPuntuacion10.setCHechizo2(My.Resources.Imagenes.extenuacion)
        ucPuntuacion10.setKDA("2/2/11")
        ucPuntuacion10.setMinions("22")
        ucPuntuacion10.setObjeto1(My.Resources.Imagenes.ojovigilantes)
        ucPuntuacion10.setObjeto2(My.Resources.Imagenes.redencion)
        ucPuntuacion10.setObjeto3(My.Resources.Imagenes.botasmovilidad)
        ucPuntuacion10.setObjeto4(My.Resources.Imagenes.mantoresistencia)
        ucPuntuacion10.setObjeto5(My.Resources.Imagenes.guardiancontrol)
        ucPuntuacion10.setObjeto6(My.Resources.Imagenes.galleta)
        ucPuntuacion10.setWard(My.Resources.Imagenes.wardquitarwards)

        UcJugador10.setFoto(My.Resources.Imagenes.ignar)
        UcJugador10.setNombre("IgNar")
        UcJugador10.setNombreReal("Dong-Geun Lee")
        UcJugador10.setRol("Support")
        UcJugador10.setNacionalidad(My.Resources.Imagenes.koreasur)
    End Sub

End Class